### ISSUE TITLE
Ability to customize CLIP keyword

### ISSUE THREAD

**Issue by tommyxps** [phguo/AskGPT#1]
Any way to change the 'clip' keyword to something else?

Thanks

**Comment by phguo** [comment]
You can change it on this workflow’s environmental variable page (top right icon like [ x ], https://www.alfredapp.com/help/workflows/advanced/variables/#environment).

**Comment by tommyxps** [comment]
> https://www.alfredapp.com/help/workflows/advanced/variables/#environment).

very nice! thank you!
