### ISSUE TITLE
v0.6 添加以下role 后没有response

### ISSUE THREAD

**Issue by tommyxps** [phguo/AskGPT#5]
添加了一个role，‘cc’ 是我的clip 关键词

*star: You are a professional resume builder who has deep knowledge in resume polishing,here are x number of  bullet points I need you to rewrite, expand and polish using 'STAR' (situation, task, ask,results) method and business language. Each bullet point should be rewrote using 'STAR', and the final resutls should have the same number of bullet points, without starting with  'Situation:', 'Task:','Action:','Results:' in the final results. here are the bullet points I need you to work on: cc  Also Highlight following skill in one of the bullet points in the results:

触发alfred5 后，输入 *star communications  没有反应，使用清除指令之后也没有反应，之后一切对gpt的问题都没有反应。重启系统问题无法解决，只有删除之后重新配置才可以。

Role 是否有字数限制？或者关键词（cc）不能出现在role里面？其他所有的参数都是默认，除了key 和python env

**Comment by phguo** [comment]
把描述里所有冒号删掉应该能暂时解决问题。和cc也有关系，建议用*cc

**Comment by phguo** [comment]
谢谢反馈！已修复。请尝试使用 https://github.com/phguo/AskGPT/releases/tag/v0.6.1 。

关键词识别顺序是 `clear_keyword -> clipboard_keyword -> roles`。因此 "cc" 出现在 role 里不会导致程序出错。

但还是建议关键字使用不太会在日常输入里出现的内容，例如默认的 `*clip` 或者简化的 `*c`。

**Comment by tommyxps** [comment]
收到，没问题了，非常感谢
