### ISSUE TITLE
I cannot get this working

### ISSUE THREAD

**Issue by DrSiriusUK** [phguo/AskGPT#6]
Hi there

I really would like to get this working but I am struggling. I have followed all the instructions but it still does not work for me.

I cannot see where it has put the gpt.py file. Where should it be?

**Comment by DrSiriusUK** [comment]
I managed to sort it all out except getting it to respond to \\gpt

**Comment by phguo** [comment]
Hi @DrSiriusUK,

To make `\\gpt` work, you need to follow these steps:

First, double click "Snippet"

<img width="645" alt="截屏2023-04-15 08 26 18" src="https://user-images.githubusercontent.com/10487750/232174254-1fbc5369-dfdb-4745-849c-46977c1daa4a.png">

Second, set the "Keyword" `gpt` and "Prefix" `\\` 

<img width="645" alt="截屏2023-04-15 08 25 43" src="https://user-images.githubusercontent.com/10487750/232174426-d2b12346-8714-4b72-9cdd-d708f4a821cb.png">

Btw, could you please share the issue that arises when implementing this workflow? This will allow me to update the README.md file for other users.

Thanks!
